spring.application.name=KamnywesoLiqourBackend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5332/kamnyweso
spring.datasource.username=admin
spring.datasource.password=admin001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Spring Mail - Resend SMTP Configuration
spring.mail.host=smtp.resend.com
spring.mail.port=587
spring.mail.username=resend
spring.mail.password=re_bSK38UZx_7W5Kb8RrUkocMdPZp3aS3jmL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b800c1c8a6fdb3a1b8b6e8b46990538c7b50b2b800c1c8a6fdb3a1b8b6e8b46990538c7b50b2b800c1c8a6fdb3a1
jwt.expiration=86400000
